spring:
  cloud:
    config:
      uri: http://localhost:8071
  application:
    name: eureka-server
server:
  port: 8071
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"