apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver-java
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: timeserver-java
  template:
    metadata:
      labels:
        pod: timeserver-java
    spec:
      containers:
      - name: timeserver-container
        image: timeserver-java:2
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 2000m
            memory: 450Mi
