spring:
  application:
    name: organization-service
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://${DB_URL}/org
#    url: jdbc:postgresql://localhost:5432/org
    username: postgres
    password: postgres
    platform: postgres
    testWhileIdle: true
    validationQuery: "SELECT 1"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_SERVICE_HOST}:${KEYCLOAK_SERVICE_PORT}/realms/two-pages/protocol/openid-connect/certs
#          jwk-set-uri: http://localhost:9080/realms/two-pages/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE_HOST}:${EUREKA_SERVICE_PORT}/eureka/