apiVersion: v1
kind: Pod
metadata:
  name: iptables-debug
spec:
  hostNetwork: true
  hostPID: true
  containers:
    - name: debug
      image: nicolaka/netshoot
      securityContext:
        privileged: true
      command: ["sleep", "3600"]